CREATE OR ALTER PROCEDURE T7Library.GetOverduePenalties
AS
SELECT B.ISBN,
	B.Title,
	BA.FirstName + N' ' + BA.LastName AS Author,
	C.DueDate,
	DATEDIFF(DAY, C.DueDate, SYSDATETIME()) AS DaysOverdue,
	CASE
		WHEN DATEDIFF(DAY, C.DueDate, SYSDATETIME()) < 7 THEN 0.25
		WHEN DATEDIFF(DAY, C.DueDate, SYSDATETIME()) BETWEEN 7 AND 14 THEN 1.00
		WHEN DATEDIFF(DAY, C.DueDate, SYSDATETIME()) > 15 THEN 4.00
	END AS PenaltyFee
FROM T7Library.Checkout C
INNER JOIN T7Library.BookCopy BC ON C.BookId = BC.BookId
INNER JOIN T7Library.Book B ON BC.ISBN = B.ISBN
INNER JOIN T7Library.BookAuthor BA ON B.ISBN = BA.ISBN
WHERE DATEDIFF(DAY, C.DueDate, SYSDATETIME()) > 0